[workspace]
members = ["core", "api", "operator", "libs/maskass", "libs/webhook", "libs/domain"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["nathaelb <pro.nathaelbonnal@gmail.com>"]
edition = "2024"
