services:
  api-build:
    environment:
      ALLOWED_ORIGINS: https://localhost:5443,https://127.0.0.1:5443
      SERVER_TLS_CERT: /etc/ferriskey/tls/localhost.crt
      SERVER_TLS_KEY: /etc/ferriskey/tls/localhost.key
      WEBAPP_URL: https://localhost:5443
    volumes:
      - ./.certs/dev-test-ssl:/etc/ferriskey/tls:ro

  webapp-build:
    environment:
      API_URL: https://localhost:3333
    ports:
      - 5443:443
    volumes:
      - ./.certs/dev-test-ssl:/etc/ssl/ferriskey:ro
      - ./front/nginx.ssl.conf:/etc/angie/http.d/default.conf:ro
