services:
  api-build:
    environment:
      ALLOWED_ORIGINS: https://localhost:5443,https://127.0.0.1:5443
      SERVER_ROOT_PATH: /api
      WEBAPP_URL: https://localhost:5443

  webapp-build:
    depends_on:
      api-build:
        condition: service_started
    environment:
      API_URL: /api
    ports:
      - 5443:443
    volumes:
      - ./.certs/dev-test-ssl:/etc/ssl/ferriskey:ro
      - ./front/nginx.ssl.conf:/etc/angie/http.d/default.conf:ro
